read description from readme.md as utf-8 to fix setup errors due to wrong encoding
error:
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 9616: character maps to <undefined>